name: Build SocialsApp APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Repository
        uses: actions/checkout@v4

      - name: Extract SocialsApp ZIP
        run: |
          ZIP=$(find . -name "*.zip" | head -1)

          if [ -z "$ZIP" ]; then
            echo "No ZIP file found!"
            exit 1
          fi

          mkdir project
          unzip "$ZIP" -d project

          APP=$(find project -name 'package.json' -exec dirname {} \; | head -1)

          if [ -z "$APP" ]; then
            echo "package.json not found!"
            exit 1
          fi

          echo "APP_DIR=$APP" >> $GITHUB_ENV

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd "$APP_DIR"
          npm install

      - name: Build Web App
        run: |
          cd "$APP_DIR"
          npm run build

      - name: Install Capacitor
        run: |
          cd "$APP_DIR"
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Sync Capacitor Android
        run: |
          cd "$APP_DIR"
          npx cap sync android

      - name: Give Gradle Permission
        run: |
          cd "$APP_DIR/android"
          chmod +x gradlew

      - name: Build Debug APK
        run: |
          cd "$APP_DIR/android"
          ./gradlew assembleDebug

      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: SocialsApp-APK
          path: "**/app/build/outputs/apk/debug/*.apk"
