name: Build Online APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          mkdir project
          unzip *.zip -d project

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Find Android Project
        run: |
          PROJECT_DIR=$(dirname "$(find project -name settings.gradle.kts | head -n 1)")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          gradle assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Online-TicTacToe-APK
          path: |
            project/**/app/build/outputs/apk/debug/*.apk
            project/**/*.apk
